### ISSUE TITLE
Desired contributions

### ISSUE THREAD

**Issue by bogdangaliceanu** [MicrosoftEdge/A11y#7]
Would you consider small code changes that improve performance and/or readability helpful? For example makings some things const, giving collections the exact capacity they need from the start, extracting methods where it makes sense etc. Or do you just want to focus on features?

Also, should PRs be based on/merged into dev or master?

**Comment by DHBrett** [comment]
Hi Bogdan, we'd be happy to accept PRs for readability or perf. The ideas you mention all make sense and should help the project. Feel free to PR any functional changes into dev.

**Comment by bogdangaliceanu** [comment]
Thank you David. I will.
